### ISSUE TITLE
Pull Stampy info directly from coda

### ISSUE THREAD

**Issue by ccstan99** [StampyAI/alignment-research-dataset#10]
Sample code on how to pull updated Stampy data from data:
https://github.com/StampyAI/stampy-nlp/blob/main/src/stampy_nlp/utilities/coda_utils.py

**Comment by Thomas-Lemoine** [comment]
Just to be sure, is this a good time to close the issue

**Comment by ccstan99** [comment]
Yep! A little trick is in your PR or commits, you can mention this issue by number to associate them.
