### ISSUE TITLE
Import rest of special docs to SQL

### ISSUE THREAD

**Issue by ccstan99** [StampyAI/alignment-research-dataset#116]
- Import the rest of the entries in special docs tab into SQL
- Scrape what we can
- Export incomplete entries
- Recruit volunteer(s) to fill in needed metadata
- Reimport back to SQL
- Integrate with https://bit.ly/ard-suggestion to simplify future process

**Comment by mruwnik** [comment]
the data should now be in sql, so it can be cleaned by the poor unfortunate souls that will do it
