### ISSUE TITLE
Add alignment_newsletter summaries

### ISSUE THREAD

**Issue by ccstan99** [StampyAI/alignment-research-dataset#17]
Before uploading to HuggingFace, we need to add the alignment_newsletter summary to the 'summary' key of the related entries where it's available. This is probably just for greaterwrong and arxiv but we'll need to double-check. alignment_newsletter.jsonl is technically not supposed to be separate subset on HF. The code to do this was in the original ARD scraper in merge_all_files(). It might have gotten lost in some of our recent updates.

**Comment by ccstan99** [comment]
Besides alignment_newsletter, importai and ml_safety_newsletter datasets are the summarizers for new entries.

**Comment by mruwnik** [comment]
can be done by running `python main.py merge_summaries`
