### ISSUE TITLE
Fix HuggingFace dataloader

### ISSUE THREAD

**Issue by ccstan99** [StampyAI/alignment-research-dataset#18]
Dataloader shows subsets for `gdocs` and `gdrive_ebooks` but no data is included in the dataset even though `gdocs.jsonl` and `gdrive_ebooks.jsonl` are non-empty.

Also, the `www.yudkowsky.net.jsonl` will be renamed `yudkowsky.net.jsonl` without the `www` in newly generated files.

<img width="1256" alt="Screenshot 2023-06-11 at 12 47 32 PM" src="https://github.com/StampyAI/alignment-research-dataset/assets/38997995/f7c5dd15-be4f-4eb2-bd17-9d0d9addc012">
<img width="382" alt="Screenshot 2023-06-11 at 12 46 10 PM" src="https://github.com/StampyAI/alignment-research-dataset/assets/38997995/e3d07162-97c1-4eec-8f5c-6e2f44562a49">

**Comment by mruwnik** [comment]
invalid files were uploaded - fixed now
