### ISSUE TITLE
Replace zip with folder refs

### ISSUE THREAD

**Issue by ccstan99** [StampyAI/alignment-research-dataset#22]
Replace references to zip file (specific examples below) to the relevant [gdrive folder](https://drive.google.com/drive/u/0/folders/1QBJPWXa9PcGhSslReLy3xHx1FwUKNr3h) instead, allowing us to add new contents to be scrape. See [gdrive_ebooks](https://github.com/StampyAI/alignment-research-dataset/tree/main/align_data/ebooks) for sample code to process files from gdrive instead of zip file. When this is done, the zip files can then be deleted from the gdrive.

- align_data/audio_transcripts
gdrive_address="https://drive.google.com/uc?id=10AXFKWskoJQg64LuMKh2JHYGqsVNEXgw"

- align_data/blogs
gdrive_address="https://drive.google.com/uc?id=14com6FTnulru3_Ek-Qni8Hg_D-VHoz", gdrive_address="https://drive.google.com/uc?id=1Z0kbDd8vDsgOH6vV9Z0XBnTQutXFJ6x-",

- align_data/ebooks
gdrive_address="https://drive.google.com/uc?id=1diZwPT_HHAPFq-4RuiLx5poKsDu10q10'

- align_data/gdocs
gdrive_address = "https://drive.google.com/uc?id=18uFLj3Vs8de6LnEE00taJAvP|8dZYRxx"

- align_data/nonarxiv_papers
gdrive_address="https://drive.google.com/uc?id=1odRHgveFh2MSUeHY3TRezmn×ZQKCsMOE"

- align_data/reports
gdrive_address="https://drive.google.com/uc?id=1TzOyQ_TTc7BptFijJiojPDkA8vDmilaN"

**Comment by mruwnik** [comment]
those links don't seem to work, but the folders can be found at https://drive.google.com/drive/folders/1QBJPWXa9PcGhSslReLy3xHx1FwUKNr3h.

**Comment by mruwnik** [comment]
The `GdocDataset` class has a `folder_from_gdrive()` method that will download a folder from gdocs which can do most of the heavy lifting for this. Check the `GDrive` class for an example of how to use it.

**Comment by ccstan99** [comment]
Sorry, I broke it when I replaced the links to the zip file. I double-checked them but apparently goofed. But yes, using the gdrive folders is the solution.
