### ISSUE TITLE
Investigate managed DB

### ISSUE THREAD

**Issue by ccstan99** [StampyAI/alignment-research-dataset#25]
Investigate using a managed DB in conjunction with the dataset to simplify tracking duplicates and other metadata with access & updates. HuggingFace documentation for reading [from_sql](https://huggingface.co/docs/datasets/loading#sql)

**Comment by ccstan99** [comment]
Having the dataset in a managed DB allows a more seamless integration between the ARD and stampy-chat, which is currently keeping a separate [sqlite db](https://github.com/StampyAI/stampy-chat/issues/40) for its tracking purposes. This would also allow us to eliminate writing to the [gsheet metadata](https://docs.google.com/spreadsheets/d/1l3azVJVukGAvZPgg0GyeqiaQe8bEMZvycBJaA8cRXf4/edit#gid=0) hassle. We might (?) still want to keep a jsonl version of readable files around for local testing before updating the central DB, so we'll need to think through & discuss the workflow a bit.

### Requirements
- ARD scraper creates & updates fields to store data, see format details below. Check with @mruwnik for any other gotchas.
- Stampy, lesswrong, alignment forum are updated daily. Others updated weekly.
- Currently ~20K entries. If we keep track of chunked text (not sure is necessary), it would be ~400K entries.
- Entries would presumably include date_created, date_revised, ensure unique ids as they are scraped
- Chatbot would query for all entries where date_embedded is empty or null, then update fields after embedding. Check with @henri123lemoine for integration requirements.
- View data so people can review contents suggest items to be added to ARD. Currently, it's using the [gsheet](https://docs.google.com/spreadsheets/d/1l3azVJVukGAvZPgg0GyeqiaQe8bEMZvycBJaA8cRXf4/edit#gid=0).
- If we continue to support [HuggingFace dataset loade](https://huggingface.co/docs/datasets/loading), which would be nice since it's a standardize way to publicly share datasets, they support loading from JSON, CSV, SQL.
- Ultimately, such a DB should also allow us to log & track stampy-chat queries that should be suggested for coda human authored answers and also flag problematic generated responses to be investigated. Maybe used by stampy-ui too

### Data Format

https://huggingface.co/datasets/StampyAI/alignment-research-dataset

All entries have the keys. below. Additional keys specified in [data loader](https://huggingface.co/datasets/StampyAI/alignment-research-dataset/blob/main/alignment-research-dataset.py)
```
DEFAULT_FEATURES = {
    'id': Value('string'),
    'source': Value('string'),
    'title': Value('string'),
    'text': Value('large_string'),
    'url': Value('string'),
    'date_published': Value(dtype='string'),
    'authors': Sequence(feature=Value(dtype='string'), length=-1),
    'summary': Sequence(feature=Value(dtype='string'), length=-1),
    'source_type': Value(dtype='string'),
}
```

### SQL vs NoSQL Considerations

SQL
- We can have just 9 required keys as columns plus a metadata column for misc keys.
- CWIS suggested looking at [Remult](https://www.youtube.com/watch?v=rEoScmSVNUE) and postgresql

NoSQL
- Follows our current data format more closely so we just need to make sure updating entries by a specific criteria and filtering different views work easily.
- TJ suggested looking at [MongoDB](https://www.mongodb.com/)

**Comment by mruwnik** [comment]
I'd recommend separating the db from the frontend and for now assuming that the process of adding new items (i.e. the frontend) is:
1. someone provides info via the current form
2. approvers manually set an `approved` column (or in some way mark rows as approved) in [the suggestions sheet](https://docs.google.com/spreadsheets/d/1pgG3HzercOhf4gniaqp3tBc3uvZnHpPhXErwHcthmbI/edit?pli=1#gid=529979647)
3. a script pulls the whole sheet every now and then and adds any new items to the database

This would allow the code to migrate to a proper database (which would be reaaally nice) without having to change too much in how things work. Then a proper frontend thingy could be added at a later date.

**Comment by mruwnik** [comment]
the main gotchas that come to mind are:
 * the `text` field can potentially be very large. Though the whole dataset is currently < 400MB so that shouldn't be a problem
 * not all datasets contain end data - some are collections of summaries. Though this is mainly an issue for the code - the database can store them the same way as all the other ones
 * primary keys are potentially sort of a hassle, in that ideally they'll be unique across the whole dataset, not just in their data type (e.g. the id of a LW post should not collide with the id of an arxiv paper). The way keys are calculated is in general similar, but a couple of datasets have slightly different rules

**Comment by ccstan99** [comment]
> I'd recommend separating the db from the frontend and for now assuming that the process of adding new items ... Then a proper frontend thingy could be added at a later date.

I was going to reply to your Discord message but documenting here's better. Ideally eventually, having a full db app is probably the right solution. For the purpose for this particular issue, I agree that we should just get a proper database without changing too much in how things currently work.

> the main gotchas that come to mind...

Added to agenda for discussion at next meeting.

**Comment by tayler6000** [comment]
@mruwnik I defer to you whether you want to use NoSQL or MySQL.  I assume MySQL will be faster than NoSQL, and there isn't a learning curve for NoSQL queries (granted an ORM might fix that), so it's up to you.

**Comment by mruwnik** [comment]
I have a prejudice against NoSQL (ORMs too, though). Both MySQL and Postgres seem to support json columns, which could contain any additional metadata, while the other, required fields have a known structure.
One issue could be the authors, which are a list of strings - they could be saved as that, or have an `authors` table and a foreign key. But then there is the issue of researchers with the same name... NoSQL wouldn't have that issue
