### ISSUE TITLE
Update audio_transcripts

### ISSUE THREAD

**Issue by ccstan99** [StampyAI/alignment-research-dataset#4]
Upload Rob Mile's [Whisper transcripts](https://github.com/johannesCmayer/rob_miles_transcriptions/) to his YouTube channel. Ask @plexish on Discord for permission as SubTitle Editor Access to YouTube.

**Comment by diziet** [comment]
I'd forked the repo with the whisper transcriptions here and ran a simple script to extract the text:

https://github.com/diziet/rob_miles_transcriptions

**Comment by ccstan99** [comment]
Thanks! I'm going to copy the discussion from Discord here for easier tracking.

When the subtitles are eventually uploaded to YouTube, then we should be able to use https://github.com/jdepoix/youtube-transcript-api found by @diziet as a better long-term solution. Ultimately, that code should be integrated into https://github.com/StampyAI/alignment-research-dataset/blob/main/align_data/audio_transcripts/audio_transcripts.py, so it can be used for scraping new content too. 

As for the output with cleaned transcripts, the current ARD code expects a file transcript.zip downloaded from https://drive.google.com/uc?id=13JiAHAWakTTNQqGEXgiL0mjsuVka4-Sm containing all the transcripts converted from otter.ai as .md files without timestamps. If we follow their convention, we can update the transcript.zip file with the cleaned copies and store it own our own Google shared drive https://drive.google.com/drive/u/2/folders/1cyP-wjiHZ4PoPnFlG19ti904cJsm5iSr.

**Comment by ProducerMatt** [comment]
Done! Though I skipped the ones that were shorts announcing events, lmk if you want those as well

**Comment by ccstan99** [comment]
Thanks so much! We'll take a look. Skipping short announcements sound like a reasonable thing to do.
