### ISSUE TITLE
Data organization between GH, gdrive, and HF

### ISSUE THREAD

**Issue by ccstan99** [StampyAI/alignment-research-dataset#42]
Remove the data directory from GitHub by adding `data` directory to .gitignore, since we're have the gdrive `data/raw` directory for all data sources. 
- Update distill to use folder gdrive instead of checking into GH
- Not sure if this helps or is the ultimate direction we want to take, but just in case... Here's a google sheets (https://docs.google.com/spreadsheets/d/1pgG3HzercOhf4gniaqp3tBc3uvZnHpPhXErwHcthmbI/edit#gid=34535092) with each tab for alignment_newsletter, arxiv, special_pages which can be updated however we eventually decide on how.
- After building dataset in fetch-dataset.yml, we should upload to gdrive as well as HuggingFace to make sure both are kept in sync

Do we need to rethink workflow permissions for uploading to gdrive / HF since we're not dealing with GH main branch any more? Maybe it's not a big deal, since people already need to have permission to upload to both gdrive & HF and run GH actions?

**Comment by mruwnik** [comment]
The database removes most of these issues, the edge cases are handled elsewhere
