### ISSUE TITLE
HF dataset viewer list row count

### ISSUE THREAD

**Issue by ccstan99** [StampyAI/alignment-research-dataset#43]
When we first set up the HF data loader, almost all datasets had a row count. Now, almost none of them do even though the contents are viewable. Maybe there's some formatting issue with individual jsonl files?

<img width="365" alt="Screenshot 2023-06-17 at 10 10 50 AM" src="https://github.com/StampyAI/alignment-research-dataset/assets/38997995/cb2369d7-03a2-4ae3-b2fd-08da89a1d56a">

**Comment by mruwnik** [comment]
requires the dataset_info in the README to be correct. This can be done automatically via 
```
datasets-cli test ./alignment-research-dataset --save_info --all_configs
```
