### ISSUE TITLE
Standardize date_published

### ISSUE THREAD

**Issue by ccstan99** [StampyAI/alignment-research-dataset#47]
All `date_published` fields should be UTC format. If only the year is available, default to Jan 1 midnight.

**Comment by Thomas-Lemoine** [comment]
Alignment Newsletter has some entries without a date, not sure why: 
Row 291: date_published is NOT in a valid format: n/a
  url: https://arxiv.org/abs/1805.08974
  source: alignment_newsletter
  title: Do Better ImageNet Models Transfer Better?
  id: ea246282c2f0050981f98afaf49ffc1e
same for row 836, 879, 916, & 1114
However, for the rest of dates, they are only the year so in UTC they were set to jan 1 at midnight.

arbital has all dates working, no n/a, and conversion to utc works well

**Comment by Thomas-Lemoine** [comment]
the html_blog currently sets the date_published to n/a by default, but is used to construct the MediumBlog class, which does define a date_published. SubstackBlog uses RSSDataset which uses HTMLDataset which uses AlignmentDataset, so it is all quite messy, but somehow it outputs the correct date_published, as does distill which also uses RSSDataset.

I get an error from running agentmodels, so I cannot verify that it has the correct format.

gdrive_ebooks had errors, and the only entry that worked for me had a date that was only in years ("2015"). I don't know if, for other entries, they are year-only as well. (Edit: https://huggingface.co/datasets/StampyAI/alignment-research-dataset/viewer/gdrive_ebooks/train indicates that some are year-only and some are not.)

**Comment by Thomas-Lemoine** [comment]
gdocs say they necessitate pandoc and have errors which prevent me from seeing the date_published.

nonarxiv_papers have 'n/a' as a date_published but there should be at least a year available somehow. Similarly for reports. Both use the GdocDataset.

The rest of the sources work and have a valid iso format.

**Comment by Thomas-Lemoine** [comment]
see #53 
```
Note that the following sources still have date_published-less elements:
source: arxiv, title: n/a, date_pub: n/a
source: gdrive_ebooks, title: out-output, date_pub: n/a
source: gwern_blog, title: It Looks Like You’re Trying To, date_pub: n/a
source: nonarxiv_papers, title: Reputations for Resolve and Hi, date_pub: n/a
source: reports, title: Energetics of The Brain and AI, date_pub: n/a
```
