### ISSUE TITLE
Filter greaterwrong

### ISSUE THREAD

**Issue by ccstan99** [StampyAI/alignment-research-dataset#5]
To ensure high quality data from sources that are automatically scraped (i.e. arbital, eaforum, lesswrong), by automatically filtering by some criteria, i.e. score, votes, karma

**Comment by ccstan99** [comment]
Only include lesswrong posts where karma and votes are both positive. Also look for tags that are AI related. @plexish may provide guidance for other relevant tags to include.

**Comment by plexish** [comment]
karma positive + at least one tag in the AI section

**Comment by henri123lemoine** [comment]
@plexish What should we do with duplicates? There are not only duplicate posts on Lesswrong/the EA Forum/the Alignment Forum, but it is also common for people to post both on Lesswrong and their personal website. One option is to simply treat them normally, and have duplicates in the dataset, with each source's sub-dataset being complete. Then, when embedding the texts, we would use simple text-similarity algorithms to remove duplicates. Another is to deal with duplicates directly.

**Comment by plexish** [comment]
@henri123lemoine Deduplicating on the embeddings stage seems fairly good, in case people want to use subsets of the dataset? But if that's technically complex, picking another way is also reasonable.

**Comment by henri123lemoine** [comment]
Great, that should be the simplest technically.

**Comment by plexish** [comment]
Priority is a fair point, it's plausible someone will want just AF, but implausible that they want just EAF. And there is some automatic crossposting which should have similar URLs, but some manual which is less reliable and may be out of sync.
