### ISSUE TITLE
Keep updated

### ISSUE THREAD

**Issue by ccstan99** [StampyAI/alignment-research-dataset#6]
The dataset should be updated regularly, maybe weekly. Should we pull from other reading lists, research labs’ list of publications, following researchers twitter feeds, recommendation form submissions? 

Some potential sources to consider are list on the [`special_indices.csv` tab on this google sheet](https://docs.google.com/spreadsheets/d/1pgG3HzercOhf4gniaqp3tBc3uvZnHpPhXErwHcthmbI/edit#gid=1275815248)

Other tools that might be helpful:

- https://arxivxplorer.com/
- https://metaphor.systems/
- https://www.explainpaper.com/
- https://www.semanticscholar.org/
- https://my.paperscape.org/

**Comment by ccstan99** [comment]
Use Jack Clark's newsletter 
https://substack.com/@importai

**Comment by plexish** [comment]
https://carado.moe/
https://generative.ink/
https://www.lesswrong.com/posts/uRosq4YtNiZxywcAq/newsletter-for-alignment-research-the-ml-safety-updates

**Comment by mruwnik** [comment]
All known datasets now get updated at least weekly, with some being updated daily
