### ISSUE TITLE
agentmodels title and url

### ISSUE THREAD

**Issue by ccstan99** [StampyAI/alignment-research-dataset#62]
The agentmodels dataset view (https://huggingface.co/datasets/StampyAI/alignment-research-dataset) indicates that 
- the `title` key should be the value in `book_title`
- the `url` key should https://agentmodels.org/chapters/1-introduction.html instead of the md file in GH
<img width="1254" alt="Screenshot 2023-06-29 at 1 13 56 AM" src="https://github.com/StampyAI/alignment-research-dataset/assets/38997995/65028329-c158-4990-8f94-c9b4438b44fb">

**Comment by henri123lemoine** [comment]
Would it not make sense for the title to be (ex) `'title': 'Modeling Agents with Probabilistic Programs - Chapter 1: Introduction',` instead of `'title': 'Modeling Agents with Probabilistic Programs',` for each chapter.

**Comment by henri123lemoine** [comment]
fixed url + title #66

**Comment by Thomas-Lemoine** [comment]
https://discord.com/channels/677546901339504640/1125882422731472896/1150201712775282840
https://discord.com/channels/677546901339504640/1125882422731472896/1150204154388688967
