### ISSUE TITLE
skip empty greaterwrong posts

### ISSUE THREAD

**Issue by Thomas-Lemoine** [StampyAI/alignment-research-dataset#73]
currently posts like https://www.alignmentforum.org/posts/5bd75cc58225bf0670374f18/paraconsistent-tiling-agents-very-early-draft, https://www.alignmentforum.org/posts/5bd75cc58225bf0670375017/provability-counterfactuals-vs-three-axioms-of-galles-and-pearl, etc. have empty 'text' content and so have the same 'id' value. We probably ought to skip these to not include them in the dataset

**Comment by mruwnik** [comment]
they should be skipped now
