### ISSUE TITLE
Update arbital links

### ISSUE THREAD

**Issue by ccstan99** [StampyAI/alignment-research-dataset#9]
Make sure arbital links and information properly updated. Leverage work done by AlignmentSearch.

**Comment by henri123lemoine** [comment]
@plex We need to discuss a few issues regarding processing of information, for Arbital and other sources.

In the current (local) version, there are a few issues:
- No date published or author(s) atm, and I have trouble finding this information, though might be possible to implement.
- Arbital hyperlinks, ex: "[1e4 AI Alignment]" in the text ('[{(opt) alias} {concept}]'). Another version is "[{alias}]", like [1] or [76]. Can be replaced by concept only, or kept the same, or replaced by normal-hyperlink notation link.
- Regular hyperlinks, ex: "[test hyperlink](https://www.url.com)". Can be replaced by linked concept only, or kept the same.
- Summaries: at the beginning of some pages' text, there's a summary with format "[summary: {actual summary}]...etc". Can be removed, or extracted and saved in the dataset with the 'summary' key, or (?).
- Todos: formatted as '[todo: {actual todo}]', can be anywhere in text, does not show up on website. Can be removed, kept as is, or reformatted slightly. There are 
- Tags: not currently implemented, though it could be worth implementing. The tag would describe the arbital subspace of the page (`ARBITAL_SUBSPACES = ['ai_alignment', 'math', 'rationality']`).
- The previous link issues are resolved.

More generally, we need to determine how much we want to pre-process in the dataset-making stage. Do we want to make it as convenient as possible for people to use the dataset directly, but miss some use cases (if for some reason someone wants to use the todos), or do we want to just keep as-is during dataset-creation and then do post-processing before creating the embeddings, or a mix of both depending on likelihood of usefulness?

**Comment by plexish** [comment]
Replies to the bits I have takes on:
-Date published and authors is kinda retrievable from edit history from actual arbital, but not the greaterwrong scrape. Author will (almost?) always be Yudkowsky for the alignment ones.
-Normal hyperlink notation seems reasonable, if that's what most documents use? Not familiar with standards around the dataset.
- Summary: Keep, maybe in the summary key. Though maybe pre-appending them to the document is actually pretty good here?
- Drop the todos.
- Tags would be kinda nice to have, but not important.


Generally, mix of both seems reasonable to me, e.g. todos are rare enough that this is likely not worth keeping, but summaries seem good?

**Comment by ccstan99** [comment]
Oh yes, let's keep the summaries in a different field where available. I was thinking of embedding those separately, which might be helpful for paper/blog searches. For papers, we can use the abstract. Some papers & blogs also have summaries from the alignment newsletters, so just make sure it's a different key. Eventually, it'd be nice for all entries in ARD to have some kind of summary generated by LLM where human written one isn't available. Semantic scholar has a TLDR for ~20 words compared to arxiv abstracts which are ~200 words.

I agree that the tags should be saved.

The hyperlinks are "within" the content or "to" the content? As long as we store a working url for citations, I don't really have an opinion on the rest.
